In [43]:
from PIL import Image
from PIL import ImageFilter

In [49]:
#image 불러내기
path="C:/Users/DSLab_2/Desktop/KakaoTalk_20210520_195357013.jpg"
path2="C:/Users/DSLab_2/Desktop/KakaoTalk_20210520_195357432.jpg"
img=Image.open(path)
img2=Image.open(path2)

In [33]:
#imag 보이기,파일이름,넓이픽셀,높이픽셀,rgb등의 색상 요소
img.show()
img.filename
img.width
img.height
img.mode

'RGB'

In [30]:
#이미지 픽셀 개수 변경,리사이징
resize_img=img.resize((img.width//2,img.height//2))
resize_img.show()

In [39]:
#이미지 자르기
cropped_img=img.crop((100,100,400,400))
cropped_img.show()

In [40]:
#이미지 회전
img.rotate(45).show()

In [42]:
#이미지 대칭 뒤집기
#이미지 회전하기
flip_img=img.transpose(Image.FLIP_LEFT_RIGHT)
flip_img.show()
flip_img2=img.transpose(Image.FLIP_TOP_BOTTOM)
flip_img2.show()
flip_img3=img.transpose(Image.ROTATE_270)
flip_img3.show()

In [44]:
#이미지 흐리기 필터. 3가지
#필터 종류가 상당히 많음.
blur_img=img.filter(ImageFilter.BLUR)
blur_img2=img.filter(ImageFilter.BoxBlur(10))
blur_img3=img.filter(ImageFilter.GaussianBlur(10))
blur_img.show()
blur_img2.show()
blur_img3.show()

In [51]:
#이미지 합치기.
new_img=Image.new("RGB",(5000,5000),300000)
new_img.paste(img,(10,10))
new_img.paste(img2,(img.width+10,10))
new_img.show()

In [54]:
#이미지 저장.
new_img.save("C:/Users/DSLab_2/hi.jpg")

In [58]:
import io
#바이트배열로 변환 후 표출
bytearr=io.BytesIO()
img.save(bytearr,format="JPEG")
print(bytearr.getvalue())
#함수로 만들편 편리하겠지?
def image_to_byte_array(image):
    imgbytearr=io.BytesIO()
    image.save(imgbytearr,format=image.format)
    imgbytearr=imgbytearr.getvalue()
    return imgbytearr

In [63]:
import numpy as np
numpy_img=np.array(img)
print(numpy_img)
print(numpy_img.shape)

[[[ 41  56   1]
  [ 52  68   5]
  [ 88 109  34]
  ...
  [ 69 101   0]
  [ 67  90  12]
  [ 78  92  57]]

 [[ 41  57   0]
  [ 68  85  17]
  [ 75  96  21]
  ...
  [ 78 111   0]
  [ 76 100  16]
  [ 72  87  48]]

 [[ 68  85  15]
  [ 53  70   0]
  [ 79  99  27]
  ...
  [ 85 119   0]
  [ 86 111  19]
  [ 72  88  43]]

 ...

 [[ 96 126   4]
  [109 137  27]
  [ 82 108   9]
  ...
  [101 126  24]
  [ 83 102  23]
  [ 84  94  57]]

 [[108 132  38]
  [108 130  48]
  [ 74  96  24]
  ...
  [106 129  38]
  [ 97 114  44]
  [100 109  78]]

 [[107 127  56]
  [109 127  69]
  [ 80  96  51]
  ...
  [117 139  56]
  [113 129  67]
  [102 110  86]]]
(1440, 1081, 3)


In [66]:
#넘파이 배열을 이미지로 변환
numpy_to_img=Image.fromarray(numpy_img,'RGB')
numpy_to_img.show()

In [70]:
#이미지 픽셀 값으로 변환
pixel_list=list(img.getdata())
print(pixel_list)
np.savetxt("pixel_type_data.txt",pixel_list,fmt='%d',delimiter=" ")

IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)



In [ ]:
#이미지의 특정 픽셀의 rgb 생상 구하는 방법
rgb_img=img.convert("RGB")
tuple_item=